name: wolof_calendar
description: Wolof Calendar companion app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.3.3+31

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  scrollable_positioned_list: ^0.3.8
  intl: any
  shared_preferences: ^2.0.7
  url_launcher: ^6.3.1
  just_audio: ^0.9.24
  audio_session: ^0.1.6+1
  font_awesome_flutter: ^10.1.0
  firebase_core: ^3.8.1
  # firebase_core:
  #   ^3.4.0
  # for web 1.0 override
  firebase_analytics: ^11.6.0
  # firebase_analytics:
  #   ^11.3.0
  # for web 1.0 override
  flutter_native_splash: ^2.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.3
  flutter_html: ^3.0.0-beta.2

  flutter_lints: ^5.0.0
  animated_box_decoration: ^0.0.7
  package_info_plus: ^8.0.2
  share_plus: ^10.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

# dependency_overrides:
#   web:
#     ^1.0.0
# for firebase plugins which have not yet gotten up to web 1.0.
# see https://github.com/firebase/flutterfire/issues/13190

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/icons/moon.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/icons/moon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audio/
    - assets/html/
    - assets/icons/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: Charis
      fonts:
        - asset: assets/fonts/CharisSILCompact-R.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
