// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3p4ZfR_avKLxph-VL82947UckPAmFQA',
    appId: '1:613913153946:web:aeb97626ce1ab40e406a23',
    messagingSenderId: '613913153946',
    projectId: 'wolof-calendar',
    authDomain: 'wolof-calendar.firebaseapp.com',
    databaseURL: 'https://wolof-calendar.firebaseio.com',
    storageBucket: 'wolof-calendar.firebasestorage.app',
    measurementId: 'G-VBLNXNXSTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlSAdSO7IxVAUsLDYV-9w6EFhrHKyLvI',
    appId: '1:613913153946:android:070f7bd7b7457ad1406a23',
    messagingSenderId: '613913153946',
    projectId: 'wolof-calendar',
    databaseURL: 'https://wolof-calendar.firebaseio.com',
    storageBucket: 'wolof-calendar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfHI_en-CqQCAQbNI_ZZbIb0WtVpyR3U',
    appId: '1:613913153946:ios:3c22e16d0015905d406a23',
    messagingSenderId: '613913153946',
    projectId: 'wolof-calendar',
    databaseURL: 'https://wolof-calendar.firebaseio.com',
    storageBucket: 'wolof-calendar.firebasestorage.app',
    iosBundleId: 'org.mbs.cal.wol',
  );

}